---
jobs:
- name: build
  public: true
  serial_groups: [version]
  plan:
  - aggregate:
    - get: pipeline-tasks
    - get: spring-initializer
      trigger: true
    - get: version
      params: {pre: rc}
  - put: version
    params: {file: version/version}
  - put: spring-initializer-image-rc
    params:
      build: spring-initializer
      tag: version/version
      tag_as_latest: false
  - put: tracker
    params:
      repos:
        - spring-initializer

- name: shipit
  public: true
  serial_groups: [version]
  plan:
  - aggregate:
    - get: pipeline-tasks
    - get: project
      resource: spring-initializer
      passed: [build]
    - get: spring-initializer-image-rc
      passed: [build]
      params: {save: true}
    - get: version
      passed: [build]
      params: {bump: final}
  - task: generate-github-release
    file: pipeline-tasks/generate-github-release/task.yml
    output_mapping: {task-output: generate-github-release-output}
  - task: generate-commitish
    file: pipeline-tasks/generate-commitish/task.yml
    output_mapping: {task-output: generate-commitish-output}
  - put: github-release
    params:
      name: generate-github-release-output/release-name
      tag: generate-github-release-output/release-tag
      commitish: generate-commitish-output/commitish
  - put: version
    params: {file: version/version}
  - put: spring-initializer-image-final
    params:
      load: spring-initializer-image-rc
      tag: version/version
      tag_as_latest: true

- name: major
  public: true
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: major, pre: rc}
  - put: version
    params: {file: version/version}

- name: minor
  public: true
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: minor, pre: rc}
  - put: version
    params: {file: version/version}

- name: patch
  public: true
  serial_groups: [version]
  plan:
  - get: version
    passed: [shipit]
    params: {bump: patch, pre: rc}
    trigger: true
  - put: version
    params: {file: version/version}

resources:
- name: pipeline-tasks
  type: git
  source:
    uri: {{pipeline-tasks-git-uri}}
    branch: {{pipeline-tasks-git-branch}}

- name: spring-initializer
  type: git
  source:
    uri: {{git-uri}}
    branch: {{git-branch}}
    private_key: {{git-private-key}}
    ignore_paths:
    - LICENSE
    - NOTICE.md
    - pipeline.yml
    - README.md

- name: github-release
  type: github-release
  source:
    access_token: {{github-release-access-token}}
    repository: spring-initializer
    user: patrickcrocker

- name: version
  type: semver
  source:
    driver: git
    initial_version: 1.0.0-rc.0
    uri: {{git-uri-semver}}
    branch: version
    file: version
    private_key: {{git-private-key}}

- name: spring-initializer-image-rc
  type: docker-image
  source:
    repository: {{docker-repository-rc}}
    username: {{docker-username}}
    password: {{docker-password}}

- name: spring-initializer-image-final
  type: docker-image
  source:
    repository: {{docker-repository-final}}
    username: {{docker-username}}
    password: {{docker-password}}

- name: tracker
  type: tracker
  source:
    token: {{tracker-api-token}}
    project_id: {{tracker-project-id}}
    tracker_url: {{tracker-url}}
